version: "3"
services:
  postgres:
    build:
      context: ./docker/postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'social_network'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
  mongo:
    build:
      context: ./docker/mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  backend:
    build:
      context: ./docker/backend
    volumes:
      - "./backend:/srv"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
      mongo:
        condition: service_started
  messenger:
    build:
      context: ./docker/messenger
    ports:
      - "3000:3000"
    volumes:
      - "./messenger:/srv"