export const MESSAGE_EVENTS = {
    SEND: 'MESSAGE_SEND',
    DELETE: 'MESSAGE_DELETE',
    UPDATE: 'MESSAGE_UPDATE',
    SENDED_SUCCESS: 'MESSAGE_SENDED_SUCCESS',
    SENDED_FAIL: 'MESSAGE_SENDED_FAIL',
    UPDATED_SUCCESS: 'MESSAGE_UPDATED_SUCCESS',
    UPDATED_FAIL: 'MESSAGE_UPDATED_FAIL',
    DELETED_SUCCESS: 'MESSAGE_DELETED_SUCCESS',
    DELETED_FAIL: 'MESSAGE_DELETED_FAIL',
}
